
@host=https://localhost:5001

POST {{host}}/auth/register
Content-Type: application/json

{
  "firstname": "Ngimdock2",
  "lastname": "Zemfack",
  "email": "ngimdock@gmail2.com",
  "password": "000000"
}